version: "3.9"
services:
  db:
    image: mysql:8.0
    ports: ["3308:3306"] # avoid conflicts on 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smm
      MYSQL_USER: smm
      MYSQL_PASSWORD: smm
    volumes: ["db_data:/var/lib/mysql"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 15

  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes: ["redis_data:/data"]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    volumes: ["minio_data:/data"]

volumes:
  db_data: {}
  redis_data: {}
  minio_data: {}
